### ISSUE TITLE
Advanced Search Improvements

### ISSUE THREAD

**Issue by kstapelfeldt** [Islandora/advanced_search#19]
As an end user, I anticipate that there is some fuzziness in each field search. If I select subject, title, etc, I should not have a phrase search, unless I've defined that using quotation marks. If I'm searching the "title" field it should be an aggregated field similar to the one Rosie implemented, and the searching in that field should use edismax. It would be good to understand and document what will happen when edismax is not turned on.

This means the search should accept words in other orders, some misspellings, missing words, wildcards, etc and return relevant results

**Comment by kylehuynh205** [comment]
This is already handled in the documentation.

![Image](https://github.com/Islandora/advanced_search/assets/7862086/bee040ee-122e-4717-a2df-75870afd4819)

**Comment by kstapelfeldt** [comment]
This is good. Will close pending more testing of the search with Bennett later in the year
