### ISSUE TITLE
Wildcard for simple/advanced search

### ISSUE THREAD

**Issue by kstapelfeldt** [Islandora/advanced_search#5]
Editing the issue title - We want wildcard for advanced search, and then Lucene search (defaulting to as fuzzy as possible in config) for the simple search.

**Comment by kylehuynh205** [comment]
Detail about wildcard searching in Solr: https://solr.apache.org/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-WildcardSearches

Wildcard searching functionality is added with commit: https://github.com/digitalutsc/advanced_search/commit/8c3bf4f47bf3635e4f759fdf7a322a374a9b9baa

Live Demo: 

Search with the following keywords on both https://core.digital.utsc.utoronto.ca/ and https://core.digital.utsc.utoronto.ca/advanced-search (with `All`):

- `network` to test dismax search then `net*` to test with wildcard.
- `diplomacy` to test dismax search then `diplo*` to test with wildcard.
- `42.114025, -96.7072294` for dismax then `42.1*` to test with wildcard. 
- `bamboo` for dismax then `ba?boo` to test with wildcard.

**Comment by kstapelfeldt** [comment]
Integration with ISLE-DC pending
