### ISSUE TITLE
New release 2.1.1

### ISSUE THREAD

**Issue by joshdentremont** [Islandora/advanced_search#56]
Could we get a 2.1.1 release? There is a commit that was merged after 2.1.0 that solves an issue I'm having - https://github.com/Islandora/advanced_search/pull/52

Without this, sorting search results causes an error to show up for users of the site

Thanks

**Comment by kayakr** [comment]
@joshdentremont I see 2.1.1 has been released https://www.drupal.org/project/advanced_search/releases/2.1.1, although unfortunately without release notes. Is your issue fixed wth 2.1.1?

**Comment by joshdentremont** [comment]
This fixed it for me. Thanks
