### ISSUE TITLE
[Github Action] Mirror to Drupal.org Gitlab stops working

### ISSUE THREAD

**Issue by kylehuynh205** [Islandora/advanced_search#58]
# About

The most recent commits are not mirrored to Drupal.org Gitlab:  https://git.drupalcode.org/project/advanced_search

* Which page does it occur on?

Visit Github actions history with the most recent commits in Github: https://github.com/Islandora/advanced_search/actions/runs/10706459936/job/29684242754

* When does this issue occur?

<img width="1747" alt="image" src="https://github.com/user-attachments/assets/299e4e55-39b7-4701-bcda-7ced2a6bd931">

* What happens?

The Access token is expired.

* What did you expect to happen?

The access token need to be renewed. 

<!--

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
    * Or you can drag and drop your file to this comment directly.

**Comment by aOelschlager** [comment]
This was talked about in the tech call today along with the other 3 Islandora repositories that have the [same issue](https://github.com/Islandora/islandora-community/wiki/September-18%2C-2024#minutes). Seth is still figuring this out.

**Comment by seth-shaw-asu** [comment]
I've been unsuccessful in my attempt to follow [the instructions](https://github.com/digitalutsc/islandora_lite_docs/wiki/9.-Troubleshooting-and-Notes#sync-github-repo-to-gitlab). If any other @Islandora/committers can take a stab at this, I'd appreciate it.

**Comment by joecorall** [comment]
I think the token has expired similar to what happened on `islandora/islandora` and `islandora/islandora_mirador`

https://islandora.slack.com/archives/G010MPTD6T1/p1722435111634389

I think the token probably needs updated.

@seth-shaw-asu - from the instructions you linked, were you able to:

> On GitHub, add the token to the secrets of the github project under `GITLAB_PASSWORD`

**Comment by seth-shaw-asu** [comment]
@joecorall, yeah, I was able to set a value for that variable on GitHub, but the token I created in GitLab still resulted in an unauthorized access error.

**Comment by aOelschlager** [comment]
This is fixed now and the project bot is working.
