### ISSUE TITLE
date range filter

### ISSUE THREAD

**Issue by kstapelfeldt** [Islandora/advanced_search#6]
available via a block (like pretty one on special.library.unlv.edu)

https://www.drupal.org/project/facets

**Comment by kylehuynh205** [comment]
**How to setup the submodule facet_range_widget**: 

- Clone the following libraries to `/libraries` directory: 
    - https://github.com/furf/jquery-ui-touch-punch
    - https://github.com/simeydotme/jquery-ui-slider-pips
- Install dependencies modules: 
    - `composer require 'drupal/jquery_ui_slider:^1.1'` (https://www.drupal.org/project/jquery_ui_slider)
    - `composer require 'drupal/jquery_ui_touch_punch:^1.0'` (https://www.drupal.org/project/jquery_ui_touch_punch)  
- Change the following in `/facets/modules/facets_range_widget.libraries.yml`:
    - Find and replace `core/jquery.ui.slider` with `jquery_ui_slider/slider` 
    - Find and replace `core/jquery.ui.touch-punch` with `jquery_ui_touch_punch/touch-punch`

**TO DO**: 

- The widget isn't currently working with Ajax enabled view.

**Comment by kylehuynh205** [comment]
Working Demo: https://core.digital.utsc.utoronto.ca/advanced-search

**Note:** 

Range Slider Widget is only work Integer field only, so, to apply for use cases: 

- For Islandora content type, there are already ETDF fields, so in Solr config, in `/admin/config/search/search-api/index/default_solr_index_islandora_lite/fields/` set the field's TYPE as Integer: 

![image](https://user-images.githubusercontent.com/7862086/135517227-cc49c952-07b2-44c5-abc0-e5e15166e9a3.png)

In the Processor tab:

<img width="792" alt="Screen Shot 2021-09-30 at 3 23 56 PM" src="https://user-images.githubusercontent.com/7862086/135517929-80a0c49e-a4e3-4904-b18f-3d9adc1b1cf3.png">

![image](https://user-images.githubusercontent.com/7862086/135517876-b77c97f1-c16c-4936-bcaf-15c2dc88a4cb.png)

- For other content types, enable Controlled Access Term module (https://github.com/Islandora/controlled_access_terms/), and create ETDF field for those content types and setup similar as above steps. 

- **Also enable Ajax for Range Slider widget with Advanced Search module by this commit:** https://github.com/digitalutsc/advanced_search/commit/2166fc96e642ad073b78094641b7ab61cdcf0022

**Comment by kstapelfeldt** [comment]
Decided not to use the slider. Our current date approach is different; we are using a form, but the form still requires validation stuff done (for example, a user can enter a negative date)

**Comment by kylehuynh205** [comment]
Validation has been added for: 
* Enter negative number 
* Enter a "To" number more than "From" number 

With the commit: 
https://github.com/digitalutsc/facets_year_range/commit/b27b305a1c77d9f01bba1d61259c23a0652dd59a
